### PR TITLE
Add support for impish (21.10)

### PR DESCRIPTION
**Pull request by ittner**
Allow deploying the charm with series impish.

### CODE REVIEW

**Comment by ittner** [comment]
Test has timed out, but I could not figure out the cause.  It seems to be happening in [this one](https://github.com/juju-solutions/charm-ubuntu/runs/5058823674?check_suite_focus=true) too.  There is no manual trigger for a re-run, however. Any idea?

**Comment by addyess** [comment]
@dannf there's conflicts that seem to be resolved?

**Comment by addyess** [comment]
it almost feels like it needs a rebase from master?

**Comment by addyess** [comment]
and i believe will need an update to `charmcraft.yaml`

**Comment by ittner** [comment]
I just rebased the branch in top of current master and it seems ok. We still have a few months of supported impish, so it seems worth of a merge.

**Comment by ittner** [comment]
impish is EOL for two weeks now, so this is obsolete.

**Pull request closed without merging**
